### PR TITLE
MMU: Fix hardcoded line size and general cleanup

### LINKED ISSUE #2567: MMU: Enable custom cache line sizes
https://github.com/sstsimulator/sst-elements/blob/f1fe079ed0aa7269bcff6b4cc06944dcfc1054c8/src/sst/elements/mmu/tlbWrapper.cc#L106

The base address translation is hardcoded to a step size of 64. When the cache uses a line size other than 64, MMU wrapper might cause accesses that straddle two cachelines. 

If the step size can be initialized from a parameter, the MMU configuration can be tuned to match the cache interface's settings.

### PR DESCRIPTION
**Pull request by gvoskuilen**
Fixes #2567 
Some formatting updates to match vanadis
Change "checkpoint" to "snapshot" to differentiate against SST checkpoint
ifdef debug output for faster simulation

### CODE REVIEW

File: src/sst/elements/mmu/simpleMMU.cc [hunk 1]
```diff
@@ -129,8 +140,10 @@ void SimpleMMU::dup( unsigned fromPid, unsigned toPid ) {
 }
 
 void SimpleMMU::flushTlb( unsigned core, unsigned hwThread ) {
+#ifdef __SST_DEBUG_OUTPUT__
     m_dbg.debug(CALL_INFO_LONG,1,0,"core=%d hwThread=%d\n",core,hwThread);
 //    sendEvent( getLink(core,"itlb"), new TlbFlushEvent( hwThread ) );
```
Comment (hughes-c) [inline src/sst/elements/mmu/simpleMMU.cc]: Is there a reason that you left this?

Comment (gvoskuilen) [reply src/sst/elements/mmu/simpleMMU.cc]: Nope, I'll clean that up at some point...
